### ISSUE TITLE
Custom comparator bug with `SortSlice()`, and `SortString()`

### ISSUE THREAD

**Issue by gonyyi** [gonyyi/gosl#19]
## Error Message

```text
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.main.func2(0x102d23a, 0x1066eb0)
        .../test.go:29 +0x67
github.com/gonyyi/gosl.SortStrings({0xc000112ee0, 0x3, 0x2}, 0xc000112ea0)
        ...github.com/gonyyi/gosl@v0.5.2/sort.go:43 +0x5e
main.main()
        .../test.go:28 +0x2b9
```

## Affected

This error is triggered when two conditions are met. 

1. Two (2) or less items in the slice
2. And uses comparator (`func(idx1, idx2 int) bool`)

This bug affects sort functions below.

- `SortSlice()`
- `SortString()`

## Cuase 

https://github.com/gonyyi/gosl/blob/7f3f8cc6802ef1755fb9f001b86c1ae6845175e7/sort.go#L14-L18
https://github.com/gonyyi/gosl/blob/7f3f8cc6802ef1755fb9f001b86c1ae6845175e7/sort.go#L41-L45

When a comparator is given, it example the comparator by examing it to avoid a bug. 
However, this became a bug itself adversally..

**Comment by gonyyi** [comment]
Remove `SortSlice()` -- `SortAny()` will replace `SortSlice()`,.

**Comment by gonyyi** [comment]
See #20

**Comment by gonyyi** [comment]
https://github.com/gonyyi/gosl/commit/58f36b06475354754801a01304395e2170aa6758 

Also removed SortSlice.
